### PR TITLE
Make much faster

### PR DESCRIPTION
**Pull request by ryanfreckleton**
I've made a few tweaks that reduce the time of the test cases from 82 seconds to 5 seconds, about a 16x improvement.

### CODE REVIEW

**Comment by foobarmus** [comment]
Great job. Can you give me a breakdown of the performance gain between:
1. KNOWN, and
2. ''.join(...)?

The reason I'm curious is because those ''.join expressions obfuscate the
logic of the main algorithm, so should be avoided if possible.

Cheers,

**Comment by ryanfreckleton** [comment]
The KNOWN cuts the runtime by 64 seconds. The elimination of concat reduces it from 18 to 5.

I've added another commit with a simplified concat function and backwards function to aid readability. I think it's a good compromise between clarity and performance.

It takes 6 seconds to run on my machine instead of the 5 using ''.join directly.

**Comment by foobarmus** [comment]
Thanks for that. If you make the following changes, I'll merge your code:

- change KNOWN to KNOWN_WORDS
- revert all other changes to word.py
- remove backwards
- use the following logic in concat

```
try:
    return ''.join(args)
except TypeError:
    return ''.join(chain(*args))
```

(chain can be imported from itertools)

**Comment by ryanfreckleton** [comment]
I used chain.from_iterable(args) instead of chain(*args) to maintain symmetry with the ''.join() in the other clause.

Besides that, everything as requested.  :-)

**Pull request merged**
